####
OPTIONS localhost:8080/login

###
POST localhost:8080/login
Content-Type: application/json

{
  "email": "11@11.com",
  "passwd": "passwd"
}
###
POST 115.29.207.183:8080/login
Content-Type: application/json

{
  "email": "11@11.com",
  "passwd": "passwd"
}

###
POST localhost:8080/register
Content-Type: application/json
yace: y

{
  "email": "{{$random.integer(100, 200)}}@11.com",
  "passwd": "passwd",
  "nickname": "nickname"
}
