// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"server/pkg/infra/repository"
	"server/pkg/repo"
	"server/routers"
	"server/routers/api"
	"server/routers/api/v1"
	"server/service"
)

// Injectors from wire.go:

func InitApp() (*routers.Server, error) {
	db := repository.InitDB()
	iUserRepo := repo.NewUserRepo(db)
	userService := service.NewUserService(iUserRepo)
	authService := api.NewAuthService(userService)
	articleService := v1.NewArticleService()
	server := routers.NewServer(authService, articleService)
	return server, nil
}
