// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"server/pkg/infra/repository"
	"server/pkg/repo/impl"
	"server/routers"
	"server/routers/api"
	"server/routers/api/v1"
	"server/service"
)

// Injectors from wire.go:

func InitApp() (*routers.Server, error) {
	db := repository.InitDB()
	iUserRepo := impl.NewUserRepo(db)
	userService := service.NewUserService(iUserRepo)
	authService := api.NewAuthService(userService)
	iArticleRepo := impl.NewArticleRepo(db)
	articleService := service.NewArticleService(iArticleRepo, iUserRepo)
	v1ArticleService := v1.NewArticleService(articleService)
	server := routers.NewServer(authService, v1ArticleService)
	return server, nil
}
